import { useMemo } from "react";
import type { ProcessIR } from "@vibestudio/ir";
import { renderDiagramSvg } from "../lib/diagramSvg";

/**
 * The confirm-screen diagram: our own SVG renderer over the exact geometry
 * that ships in the exported .bpmn file. Pure markup — scales to its box via
 * viewBox, no viewer library, nothing to measure or fit.
 */
export function ProcessDiagram({ ir }: { ir: ProcessIR }) {
  const svg = useMemo(() => renderDiagramSvg(ir), [ir]);
  // Content is generated by our renderer with every label XML-escaped.
  return <div className="diagram-wrap" dangerouslySetInnerHTML={{ __html: svg }} />;
}
