/**
 * Prompt content for the in-app Haiku agent, plus the kick-off prompt that
 * ships in the output bundle. The model is constrained twice: these
 * instructions, and a forced tool call whose input_schema is the canonical
 * Process IR JSON Schema (Anthropic tool schemas accept it as-is; unknown
 * keywords are ignored). The deterministic validator remains the judge —
 * anything the schema can't express comes back as formatFeedback and drives
 * the self-correction rounds in lib/agent.ts.
 */
import { formatFeedback, type ValidationReport } from "@vibestudio/ir";
import type { ClarifyingQuestion } from "@vibestudio/ir";

export const ANALYST_SYSTEM = `You are a business-process analyst inside VibeStudio. You convert plain-language process descriptions from non-technical people into VibeStudio Process IR v1 documents, and you refine those documents as the person answers questions or gives corrections.

Rules for every document you emit:
- All ids are kebab-case (lowercase letters, digits, single hyphens) and unique across the whole document.
- Actors become lanes (kind: human, system, or external). Every node lives in a lane.
- Tasks have exactly one incoming and one outgoing flow. All branching and merging happens in explicit gateways (exclusiveGateway = XOR, parallelGateway = AND, inclusiveGateway = OR), each either a "split" or a "join".
- Parallel and inclusive joins declare the split they close via pairs_with.
- Edges leaving an exclusive/inclusive split carry a condition (or is_default: true on exactly one branch). Every edge has a data_contract listing the data objects it carries.
- Give tasks Given/When/Then acceptance_criteria when the description states or clearly implies them.
- Mark anything you inferred with provenance {"status": "inferred"} and anything you guessed with {"status": "assumed"}.
- DO NOT invent facts. Where the description is silent (field lists, conditions, integrations), leave the detail out and add an entry to requirements.open_questions instead — the person will be asked.
- Keep names short and human (they appear in a diagram); put detail in descriptions.

Always answer by calling the emit_process_ir tool with the complete document.`;

export function buildGeneratePrompt(description: string): string {
  return `Convert this process description into a Process IR document:

"""
${description.trim()}
"""`;
}

export interface AnsweredQuestion {
  question: ClarifyingQuestion;
  answer: string;
}

export function buildUpdatePrompt(
  irText: string,
  report: ValidationReport | undefined,
  answered: AnsweredQuestion[],
  skippedQuestions: ClarifyingQuestion[],
  userFeedback?: string
): string {
  const parts: string[] = ["Update the Process IR document below and emit the complete updated document.", ""];
  if (userFeedback?.trim()) {
    parts.push("The person reviewed the diagram and says:", `"""`, userFeedback.trim(), `"""`, "Work their corrections into the document. Anything they state becomes provenance \"stated\".", "");
  }
  if (answered.length > 0) {
    parts.push("They answered these questions — work each answer in (fill acceptance criteria, schemas, conditions, integrations; set answered: true and record the answer on matching open_questions entries; upgrade provenance to \"stated\" and set confirmed: true on assumptions their answer confirms):", "");
    for (const { question, answer } of answered) {
      parts.push(`Q (${question.affects.join(", ") || question.theme}): ${question.question}`);
      parts.push(`A: ${answer.trim()}`);
      parts.push("");
    }
  }
  if (skippedQuestions.length > 0) {
    parts.push("They skipped these questions. Resolve each with the most reasonable assumption so the document is complete — mark everything you decide with provenance {\"status\": \"assumed\"} and add/keep a requirements.assumptions entry so it is surfaced for review. Do not leave these as open questions:", "");
    for (const q of skippedQuestions) parts.push(`- ${q.question}`);
    parts.push("");
  }
  if (report && report.counts.error + report.counts.warning > 0) {
    parts.push("The deterministic validator reported the following. Fix every error; fix warnings when you can without inventing facts:", "", formatFeedback(report), "");
  }
  parts.push("Current document:", irText.trim());
  return parts.join("\n");
}

export function buildFixPrompt(irText: string, report: ValidationReport): string {
  return `The document you emitted has validation errors. Fix them all and emit the complete corrected document.

${formatFeedback(report)}

Current document:
${irText.trim()}`;
}

/** The prompt a coding agent gets pointed at the downloaded bundle with. */
export function buildKickoffPrompt(processId: string): string {
  return `This folder contains a complete, machine-readable build plan for the process "${processId}", generated by VibeStudio from a validated Process IR.

Work through it like this:
1. Read README.html for the human overview, then plan/graph-plan.json — it is the source of truth for what to build.
2. Build one work packet at a time, in the order given by build_order. Each packet in packets[] is self-contained: its inputs[] and outputs[] are data contracts (with JSON Schemas embedded in data_schemas), and its acceptance_criteria are the definition of done.
3. Consult speckit/spec.md for the human-written detail of the packet you are on, and speckit/contracts/ for the contract of every flow you touch.
4. Gateways are not work: implement the routing table in graph-plan.json routing[] in your controller/orchestrator layer, never inside a task.
5. Loops are declared in loops[] with their exit conditions — implement the exit condition exactly; never loop unconditionally.
6. After each packet, verify its acceptance criteria before moving on.
7. DOCUMENTATION DUTY — the folder ships notes/troubleshooting.md and notes/codebase.md. They are deliverables equal to the code. Their header says the builder is the intended editor: that is you — the "do not edit" rule in other generated files does not apply to these two. Every editing task below is deliberately one-packet-sized:
   a. HOW TO FIND YOUR MARKERS: every marker is self-identifying — [TO FILL <owner-id>: instructions]. After you finish a packet and its acceptance criteria pass, search both notes files for "[TO FILL <that packet's id>" and complete each hit exactly as its own instructions say, in plain non-developer language. A marker whose owner merely begins with your packet's id (e.g. "<id> hand-off", "<id> start-wiring") belongs to your packet too — the never-touch rule below applies only to markers of OTHER steps, decisions, loops, or data. Never touch those.
   b. ROUTING IS PART OF THE PACKET SITTING: wiring a step's outbound routing (its hand-off, and any decision/fan-out/loop routing immediately after it) into the orchestrator happens in that step's packet sitting, BEFORE the marker pass. For the FIRST step, the wiring that starts the process on its trigger event is also part of that packet's sitting. Then, in that same sitting, ALSO search both notes files for "[TO FILL <each decision or fan-out id you just wired>" and "[TO FILL loop <each loop id whose exit you just wired>" and complete those hits — every routing marker's own text confirms which sitting it belongs to. The per-task lines inside the Loops section ("… updates … during the loop — where:") are owned by that task's id and are found by that packet's normal 7a search.
   c. DATA MARKERS: when you create a model/table/store — inside a step packet or in an early scaffolding sitting — search both notes files for "[TO FILL data <its id>" in that same sitting and complete the hits (skip any marked "(finishing step)").
   d. FINISHING (bounded — never load everything at once): after the final packet, (1) write the "How it all runs" section by reading ONLY the already-filled per-step sections of notes/codebase.md plus your orchestrator entry point (entry point file first, 3–6 sentences); (2) search both notes files for "(finishing step)" and complete each such marker the same way — from the already-filled sections, never the whole codebase; (3) verify section by section: open one section plus only the file(s) it names, check every statement against that code, fix, move on. The build is NOT complete while any [TO FILL] marker remains anywhere.

You never need the whole project in context: one packet plus its contracts is always enough — and every documentation task above is scoped the same way.`;
}
